### ISSUE TITLE
how to Get thick signature using jSignature?

### ISSUE THREAD

**Issue by patelsumit5192** [brinley/jSignature#149]
Notes: I tried all questions & answers related this topic. Additionally and I tried related questions and try to solve it but no the success. So please read my question thoroughly.

i am using Jsignature . i want to Get thick Signature after Draw signature. I know set value lineWidth set value '2' or '3' but my requirement draw Signature lineWidth : 1 and get thick signature.

i set linewidth 2 or 3 around then the signature is Draw is not Cleary some horizontal line are there. This Problem arises in IE and another browser

**Comment by brinley** [comment]
Linewidth should create the thick line that you seem to be describing. The horizontal lines is most likely caused by a different issue with newer browser where the logic to save and connect the pointer coordinates needs to be updated.

Do you not have the same horizontal line issue where linewidth is 1 in browsers that have issues when linewidth > 1?
